# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for main and preview branch
  push:
    branches: 
    - main 
    - archive 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "Build-Main" and "Build-Preview"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: dynamsoft-docs/Docs-Template-Repo/.github/workflows/called-workflow-build-sync-production.yml@main
    with:
      doc-repo: document-normalizer-docs
      doc-url: document-normalizer/docs/core
    secrets: inherit

  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    uses: dynamsoft-docs/Docs-Template-Repo/.github/workflows/called-workflow-build-sync-testing.yml@preview
    with:
      doc-repo: document-normalizer-docs
      doc-url: document-normalizer/docs/core
    secrets: inherit

  Build-Archive:
    if: ${{ github.ref == 'refs/heads/archive' }}
    uses: dynamsoft-docs/Docs-Template-Repo/.github/workflows/called-workflow-build-sync-archive.yml@archive
    with:
      doc-repo: document-normalizer-docs
      doc-url: document-normalizer/docs-archive/core
    secrets: inherit
